server:
  port: 8088
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    context-path: /api
    session:
      timeout: PT60M
spring:
  application:
    name: qianqiu-cloud
  servlet:
    multipart:
      max-file-size: 200MB      # 上传单个文件的大小
      max-request-size: 400MB  # 整个请求能上传的文件大小
#邮箱配置
  mail:
    host: smtp.qq.com
    username: 2799611325@qq.com
    password: wecqujveyysgdfif

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/qianqiu-cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 连接校验查询
      validation-query: SELECT 1
      # 最大可移除空闲连接时间（毫秒）
      max-evictable-idle-time-millis: 1800000
      # 连接错误后重试的间隔时间（毫秒）
      time-between-connect-error-millis: 600000
#redis配置
  data:
    redis:
      host: 192.168.88.128
      port: 6379
      database: 5
      password: cwj326326 # Redis服务器连接密码（默认为空）
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数
          max-idle: 8 # 连接池最大空闲连接数
          min-idle: 0 # 连接池最小空闲连接数
          max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制

logging:
  level:
    com.qianqiu.clouddisk.mbg.mbg_mapper: debug
    root: info
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
save:
  fileRootPackage: ./fileRootPackage
#swagger
version: 0.0.1
springdoc:
  packages-to-scan: com.qianqiu.clouddisk.controller
  api-docs:
    path: /qianqiu/api-docs
  swagger-ui:
    path: /qianqiu/api
    doc-expansion: none
#minio
minio:
  endpoint: http://192.168.88.128:9000/ # MinIO服务所在地址
  defaultBucketName: default # 默认桶
  accessKey: minioadmin # 访问的key
  secretKey: minioadmin # 访问的秘钥
  defaultSliceBucketName: slice
#ffmpegPath地址
ffmpegPath: E:/JavaStudySource/otherSoftware/ffmpeg-6.1.1-essentials_build/bin/ffmpeg.exe